services:
  - type: web
    name: wheels-back
    plan: free
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d46oatu3jp1c73amj0tg-a/wheelsdb
      - key: DATABASE_USERNAME
        value: wheelsdb_user
      - key: DATABASE_PASSWORD
        value: HhLreDB2CEa8P7TEYpKlPkihzb48k6Sj
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/wheels-0.0.1-SNAPSHOT.jar"
    runtime: docker
    docker:
      image: eclipse-temurin:17-jdk


